# Generated by Django 3.0.4 on 2020-03-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0003_auto_20200323_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(blank='[Song name]', max_length=100, null='[Song name]'),
        ),
    ]
