# Generated by Django 3.0.4 on 2020-03-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0004_auto_20200323_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='preview_url',
            field=models.TextField(blank='[preview url]'),
        ),
    ]
